import { isMobilePhone } from "class-validator";

export class CellphoneUtil {
  protected isFormatted: boolean = false;

  private countries = {
    AD: { locale: "ca-AD", code: "376" },
    AE: { locale: "ar-AE", code: "971" },
    AF: { locale: null, code: "93" },
    AG: { locale: "en-AG", code: "1" },
    AI: { locale: "en-AI", code: "1" },
    AL: { locale: "sq-AL", code: "355" },
    AM: { locale: "hy-AM", code: "374" },
    AN: { locale: "nl-AN", code: null },
    AO: { locale: "pt-AO", code: "244" },
    AQ: { locale: "und-AQ", code: null },
    AR: { locale: "es-AR", code: "54" },
    AS: { locale: "en-AS", code: "1" },
    AT: { locale: "de-AT", code: "43" },
    AU: { locale: "en-AU", code: "61" },
    AW: { locale: "nl-AW", code: "297" },
    AX: { locale: "sv-AX", code: "358" },
    AZ: { locale: "az-Latn-AZ", code: "994" },
    BA: { locale: "bs-BA", code: "387" },
    BB: { locale: "en-BB", code: "1" },
    BD: { locale: "bn-BD", code: "880" },
    BE: { locale: "nl-BE", code: "32" },
    BF: { locale: "fr-BF", code: "226" },
    BG: { locale: "bg-BG", code: "359" },
    BH: { locale: "ar-BH", code: "973" },
    BI: { locale: "fr-BI", code: "257" },
    BJ: { locale: "fr-BJ", code: "229" },
    BL: { locale: "fr-BL", code: "590" },
    BM: { locale: "en-BM", code: "1" },
    BN: { locale: "ms-BN", code: "673" },
    BO: { locale: "es-BO", code: "591" },
    BQ: { locale: "nl-BQ", code: "599" },
    BR: { locale: "pt-BR", code: "55" },
    BS: { locale: "en-BS", code: "1" },
    BT: { locale: "dz-BT", code: "975" },
    BV: { locale: "und-BV", code: null },
    BW: { locale: "en-BW", code: "267" },
    BY: { locale: "be-BY", code: "375" },
    BZ: { locale: "en-BZ", code: "501" },
    CA: { locale: "en-CA", code: "1" },
    CC: { locale: "ms-CC", code: "61" },
    CD: { locale: "fr-CD", code: "243" },
    CF: { locale: "fr-CF", code: "236" },
    CG: { locale: "fr-CG", code: "242" },
    CH: { locale: "de-CH", code: "41" },
    CI: { locale: "fr-CI", code: "225" },
    CK: { locale: "en-CK", code: "682" },
    CL: { locale: "es-CL", code: "56" },
    CM: { locale: "fr-CM", code: "237" },
    CN: { locale: "zh-CN", code: "86" },
    CO: { locale: "es-CO", code: "57" },
    CR: { locale: "es-CR", code: "506" },
    CU: { locale: "es-CU", code: "53" },
    CV: { locale: "pt-CV", code: "238" },
    CW: { locale: "nl-CW", code: "599" },
    CX: { locale: "en-CX", code: "61" },
    CY: { locale: "el-CY", code: "357" },
    CZ: { locale: "cs-CZ", code: "420" },
    DE: { locale: "de-DE", code: "49" },
    DJ: { locale: "fr-DJ", code: "253" },
    DK: { locale: "da-DK", code: "45" },
    DM: { locale: "en-DM", code: "1" },
    DO: { locale: "es-DO", code: "1" },
    DZ: { locale: "ar-DZ", code: "213" },
    EC: { locale: "es-EC", code: "593" },
    EE: { locale: "et-EE", code: "372" },
    EG: { locale: "ar-EG", code: "20" },
    EH: { locale: "ar-EH", code: "212" },
    ER: { locale: "ti-ER", code: "291" },
    ES: { locale: "es-ES", code: "34" },
    ET: { locale: "am-ET", code: "251" },
    FI: { locale: "fi-FI", code: "358" },
    FJ: { locale: "en-FJ", code: "679" },
    FK: { locale: "en-FK", code: "500" },
    FM: { locale: "en-FM", code: "691" },
    FO: { locale: "fo-FO", code: "298" },
    FR: { locale: "fr-FR", code: "33" },
    GA: { locale: "fr-GA", code: "241" },
    GB: { locale: "en-GB", code: "44" },
    GD: { locale: "en-GD", code: "1" },
    GE: { locale: "ka-GE", code: "995" },
    GF: { locale: "fr-GF", code: "594" },
    GG: { locale: "en-GG", code: "44" },
    GH: { locale: "en-GH", code: "233" },
    GI: { locale: "en-GI", code: "350" },
    GL: { locale: "kl-GL", code: "299" },
    GM: { locale: "en-GM", code: "220" },
    GN: { locale: "fr-GN", code: "224" },
    GP: { locale: "fr-GP", code: "590" },
    GQ: { locale: "es-GQ", code: "240" },
    GR: { locale: "el-GR", code: "30" },
    GS: { locale: "en-GS", code: null },
    GT: { locale: "es-GT", code: "502" },
    GU: { locale: "en-GU", code: "1" },
    GW: { locale: "pt-GW", code: "245" },
    GY: { locale: "en-GY", code: "592" },
    HK: { locale: "zh-HK", code: "852" },
    HM: { locale: "und-HM", code: null },
    HN: { locale: "es-HN", code: "504" },
    HR: { locale: "hr-HR", code: "385" },
    HT: { locale: "fr-HT", code: "509" },
    HU: { locale: "hu-HU", code: "36" },
    ID: { locale: "id-ID", code: "62" },
    IE: { locale: "en-IE", code: "353" },
    IL: { locale: "he-IL", code: "972" },
    IM: { locale: "gv-IM", code: "44" },
    IN: { locale: "hi-IN", code: "91" },
    IO: { locale: "en-IO", code: "246" },
    IQ: { locale: "ar-IQ", code: "964" },
    IR: { locale: "fa-IR", code: "98" },
    IS: { locale: "is-IS", code: "354" },
    IT: { locale: "it-IT", code: "39" },
    JE: { locale: "en-JE", code: "44" },
    JM: { locale: "en-JM", code: "1" },
    JO: { locale: "ar-JO", code: "962" },
    JP: { locale: "ja-JP", code: "81" },
    KE: { locale: "sw-KE", code: "254" },
    KG: { locale: "ky-KG", code: "996" },
    KH: { locale: "km-KH", code: "855" },
    KI: { locale: "en-KI", code: "686" },
    KM: { locale: "ar-KM", code: "269" },
    KN: { locale: "en-KN", code: "1" },
    KP: { locale: "ko-KP", code: "850" },
    KR: { locale: "ko-KR", code: "82" },
    KW: { locale: "ar-KW", code: "965" },
    KY: { locale: "en-KY", code: "1" },
    KZ: { locale: "kk-KZ", code: "7" },
    LA: { locale: "lo-LA", code: "856" },
    LB: { locale: "ar-LB", code: "961" },
    LC: { locale: "en-LC", code: "1" },
    LI: { locale: "de-LI", code: "423" },
    LK: { locale: "si-LK", code: "94" },
    LR: { locale: "en-LR", code: "231" },
    LS: { locale: "st-LS", code: "266" },
    LT: { locale: "lt", code: "370" },
    LU: { locale: "lb-LU", code: "352" },
    LV: { locale: "lv-LV", code: "371" },
    LY: { locale: "ar-LY", code: "218" },
    MA: { locale: "ar-MA", code: "212" },
    MC: { locale: "fr-MC", code: "377" },
    MD: { locale: "ro-MD", code: "373" },
    ME: { locale: "sr-Latn-ME", code: "382" },
    MF: { locale: "fr-MF", code: "590" },
    MG: { locale: "mg-MG", code: "261" },
    MH: { locale: "mh-MH", code: "692" },
    MK: { locale: "mk-MK", code: "389" },
    ML: { locale: "fr-ML", code: "223" },
    MM: { locale: "my-MM", code: "95" },
    MN: { locale: "mn-Cyrl-MN", code: "976" },
    MO: { locale: "zh-MO", code: "853" },
    MP: { locale: "en-MP", code: "1" },
    MQ: { locale: "fr-MQ", code: "596" },
    MR: { locale: "ar-MR", code: "222" },
    MS: { locale: "en-MS", code: "1" },
    MT: { locale: "mt-MT", code: "356" },
    MU: { locale: "en-MU", code: "230" },
    MV: { locale: "dv-MV", code: "960" },
    MW: { locale: "ny-MW", code: "265" },
    MX: { locale: "es-MX", code: "52" },
    MY: { locale: "ms-MY", code: "60" },
    MZ: { locale: "pt-MZ", code: "258" },
    NA: { locale: "en-NA", code: "264" },
    NC: { locale: "fr-NC", code: "687" },
    NE: { locale: "fr-NE", code: "227" },
    NF: { locale: "en-NF", code: "672" },
    NG: { locale: "en-NG", code: "234" },
    NI: { locale: "es-NI", code: "505" },
    NL: { locale: "nl-NL", code: "31" },
    NO: { locale: "nb-NO", code: "47" },
    NP: { locale: "ne-NP", code: "977" },
    NR: { locale: "na-NR", code: "674" },
    NU: { locale: "niu-NU", code: "683" },
    NZ: { locale: "en-NZ", code: "64" },
    OM: { locale: "ar-OM", code: "968" },
    PA: { locale: "es-PA", code: "507" },
    PE: { locale: "es-PE", code: "51" },
    PF: { locale: "fr-PF", code: "689" },
    PG: { locale: "en-PG", code: "675" },
    PH: { locale: "en-PH", code: "63" },
    PK: { locale: "ur-PK", code: "92" },
    PL: { locale: "pl-PL", code: "48" },
    PM: { locale: "fr-PM", code: "508" },
    PN: { locale: "en-PN", code: null },
    PR: { locale: "es-PR", code: "1" },
    PS: { locale: "ar-PS", code: "970" },
    PT: { locale: "pt-PT", code: "351" },
    PW: { locale: "pau-PW", code: "680" },
    PY: { locale: "es-PY", code: "595" },
    QA: { locale: "ar-QA", code: "974" },
    RE: { locale: "fr-RE", code: "262" },
    RO: { locale: "ro-RO", code: "40" },
    RS: { locale: "sr-Latn-RS", code: "381" },
    RU: { locale: "ru-RU", code: "7" },
    RW: { locale: "rw-RW", code: "250" },
    SA: { locale: "ar-SA", code: "966" },
    SB: { locale: "en-SB", code: "677" },
    SC: { locale: "fr-SC", code: "248" },
    SD: { locale: "ar-SD", code: "249" },
    SE: { locale: "sv-SE", code: "46" },
    SG: { locale: "en-SG", code: "65" },
    SH: { locale: "en-SH", code: "290" },
    SI: { locale: "sl-SI", code: "386" },
    SJ: { locale: "nb-SJ", code: "47" },
    SK: { locale: "sk-SK", code: "421" },
    SL: { locale: "kri-SL", code: "232" },
    SM: { locale: "it-SM", code: "378" },
    SN: { locale: "fr-SN", code: "221" },
    SO: { locale: "so-SO", code: "252" },
    SR: { locale: "nl-SR", code: "597" },
    SS: { locale: "ar-SS", code: "211" },
    ST: { locale: "pt-ST", code: "239" },
    SV: { locale: "es-SV", code: "503" },
    SX: { locale: "nl-SX", code: "1" },
    SY: { locale: "ar-SY", code: "963" },
    SZ: { locale: "ss-SZ", code: "268" },
    TC: { locale: "en-TC", code: "1" },
    TD: { locale: "fr-TD", code: "235" },
    TF: { locale: "und-TF", code: null },
    TG: { locale: "fr-TG", code: "228" },
    TH: { locale: "th-TH", code: "66" },
    TJ: { locale: "tg-Cyrl-TJ", code: "992" },
    TK: { locale: "tkl-TK", code: "690" },
    TL: { locale: "pt-TL", code: "670" },
    TM: { locale: "tk-TM", code: "993" },
    TN: { locale: "ar-TN", code: "216" },
    TO: { locale: "to-TO", code: "676" },
    TR: { locale: "tr-TR", code: "90" },
    TT: { locale: "en-TT", code: "1" },
    TV: { locale: "tvl-TV", code: "688" },
    TW: { locale: "zh-TW", code: "886" },
    TZ: { locale: "sw-TZ", code: "255" },
    UA: { locale: "uk-UA", code: "380" },
    UG: { locale: "sw-UG", code: "256" },
    UM: { locale: "en-UM", code: null },
    US: { locale: "en-US", code: "1" },
    UY: { locale: "es-UY", code: "598" },
    UZ: { locale: "uz-Latn-UZ", code: "998" },
    VA: { locale: "it-VA", code: "39" },
    VC: { locale: "en-VC", code: "1" },
    VE: { locale: "es-VE", code: "58" },
    VG: { locale: "en-VG", code: "1" },
    VI: { locale: "en-VI", code: "1" },
    VN: { locale: "vi-VN", code: "84" },
    VU: { locale: "bi-VU", code: "678" },
    WF: { locale: "fr-WF", code: "681" },
    WS: { locale: "sm-WS", code: "685" },
    YE: { locale: "ar-YE", code: "967" },
    YT: { locale: "fr-YT", code: "262" },
    ZA: { locale: "en-ZA", code: "27" },
    ZM: { locale: "en-ZM", code: "260" },
    ZW: { locale: "sn-ZW", code: "263" },
  };

  constructor(protected number: string, protected countryAlphaTwo: string) {
    if (!this.countries.hasOwnProperty(countryAlphaTwo)) {
      throw `country alphaTwo '${countryAlphaTwo}' is not valid!`;
    }
  }

  public isValid(): boolean {
    return isMobilePhone(
      this.number,
      this.countries[this.countryAlphaTwo].locale,
    );
  }

  public fullNumber(): string {
    if (!this.isFormatted) {
      this.format();
    }
    return `+${
      this.countries[this.countryAlphaTwo]["code"]
    }-${this.number.substring(1)}`;
  }

  public localNumber(): string {
    if (!this.isFormatted) {
      this.format();
    }
    return `${this.number}`;
  }

  public format(): this {
    // TODO: implement the format method
    this.isFormatted = true;
    return this;
  }
}
