import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { Country } from "./entities/country.entity";

export default class CountrySeeder {
  private readonly data = [
    {
      name: "افغانستان",
      nameEn: "Afghanistan",
      slug: "afghanistan",
      alphaTwo: "AF",
      iso: "AFG",
      phonePrefix: "4",
      sort: 10,
      isActive: false,
      latitude: 33,
      longitude: 65,
    },
    {
      name: "جزایر آلند",
      nameEn: "Åland Islands",
      slug: "aland-islands",
      alphaTwo: "AX",
      iso: "ALA",
      phonePrefix: "358",
      sort: 10,
      isActive: false,
      latitude: null,
      longitude: null,
    },
    {
      name: "آلبانی",
      nameEn: "Albania",
      slug: "albania",
      alphaTwo: "AL",
      iso: "ALB",
      phonePrefix: "8",
      sort: 10,
      isActive: false,
      latitude: 41,
      longitude: 20,
    },
    {
      name: "الجزایر",
      nameEn: "Algeria",
      slug: "algeria",
      alphaTwo: "DZ",
      iso: "DZA",
      phonePrefix: "12",
      sort: 10,
      isActive: false,
      latitude: 28,
      longitude: 3,
    },
    {
      name: "ساموای آمریکا",
      nameEn: "American Samoa",
      slug: "american-samoa",
      alphaTwo: "AS",
      iso: "ASM",
      phonePrefix: "16",
      sort: 10,
      isActive: false,
      latitude: -14.33,
      longitude: -170,
    },
    {
      name: "آندورا",
      nameEn: "Andorra",
      slug: "andorra",
      alphaTwo: "AD",
      iso: "AND",
      phonePrefix: "20",
      sort: 10,
      isActive: false,
      latitude: 42.5,
      longitude: 1.6,
    },
    {
      name: "آنگولا",
      nameEn: "Angola",
      slug: "angola",
      alphaTwo: "AO",
      iso: "AGO",
      phonePrefix: "24",
      sort: 10,
      isActive: false,
      latitude: -12.5,
      longitude: 18.5,
    },
    {
      name: "آنگویلا",
      nameEn: "Anguilla",
      slug: "anguilla",
      alphaTwo: "AI",
      iso: "AIA",
      phonePrefix: "660",
      sort: 10,
      isActive: false,
      latitude: 18.25,
      longitude: -63.17,
    },
    {
      name: "جنوبگان",
      nameEn: "Antarctica",
      slug: "antarctica",
      alphaTwo: "AQ",
      iso: "ATA",
      phonePrefix: "10",
      sort: 10,
      isActive: false,
      latitude: -90,
      longitude: 0,
    },
    {
      name: "آنتیگوا و باربودا",
      nameEn: "Antigua and Barbuda",
      slug: "antigua-and-barbuda",
      alphaTwo: "AG",
      iso: "ATG",
      phonePrefix: "28",
      sort: 10,
      isActive: false,
      latitude: 17.05,
      longitude: -61.8,
    },
    {
      name: "آرژانتین",
      nameEn: "Argentina",
      slug: "argentina",
      alphaTwo: "AR",
      iso: "ARG",
      phonePrefix: "32",
      sort: 10,
      isActive: false,
      latitude: -34,
      longitude: -64,
    },
    {
      name: "ارمنستان",
      nameEn: "Armenia",
      slug: "armenia",
      alphaTwo: "AM",
      iso: "ARM",
      phonePrefix: "51",
      sort: 10,
      isActive: false,
      latitude: 40,
      longitude: 45,
    },
    {
      name: "آروبا",
      nameEn: "Aruba",
      slug: "aruba",
      alphaTwo: "AW",
      iso: "ABW",
      phonePrefix: "533",
      sort: 10,
      isActive: false,
      latitude: 12.5,
      longitude: -69.97,
    },
    {
      name: "استرالیا",
      nameEn: "Australia",
      slug: "australia",
      alphaTwo: "AU",
      iso: "AUS",
      phonePrefix: "36",
      sort: 10,
      isActive: false,
      latitude: -27,
      longitude: 133,
    },
    {
      name: "اتریش",
      nameEn: "Austria",
      slug: "austria",
      alphaTwo: "AT",
      iso: "AUT",
      phonePrefix: "40",
      sort: 10,
      isActive: false,
      latitude: 47.33,
      longitude: 13.33,
    },
    {
      name: "جمهوری آذربایجان",
      nameEn: "Azerbaijan",
      slug: "azerbaijan",
      alphaTwo: "AZ",
      iso: "AZE",
      phonePrefix: "31",
      sort: 10,
      isActive: false,
      latitude: 40.5,
      longitude: 47.5,
    },
    {
      name: "باهاما",
      nameEn: "Bahamas",
      slug: "bahamas",
      alphaTwo: "BS",
      iso: "BHS",
      phonePrefix: "44",
      sort: 10,
      isActive: false,
      latitude: 24.25,
      longitude: -76,
    },
    {
      name: "بحرین",
      nameEn: "Bahrain",
      slug: "bahrain",
      alphaTwo: "BH",
      iso: "BHR",
      phonePrefix: "48",
      sort: 10,
      isActive: false,
      latitude: 26,
      longitude: 50.55,
    },
    {
      name: "بنگلادش",
      nameEn: "Bangladesh",
      slug: "bangladesh",
      alphaTwo: "BD",
      iso: "BGD",
      phonePrefix: "50",
      sort: 10,
      isActive: false,
      latitude: 24,
      longitude: 90,
    },
    {
      name: "باربادوس",
      nameEn: "Barbados",
      slug: "barbados",
      alphaTwo: "BB",
      iso: "BRB",
      phonePrefix: "52",
      sort: 10,
      isActive: false,
      latitude: 13.17,
      longitude: -59.53,
    },
    {
      name: "بلاروس",
      nameEn: "Belarus",
      slug: "belarus",
      alphaTwo: "BY",
      iso: "BLR",
      phonePrefix: "112",
      sort: 10,
      isActive: false,
      latitude: 53,
      longitude: 28,
    },
    {
      name: "بلژیک",
      nameEn: "Belgium",
      slug: "belgium",
      alphaTwo: "BE",
      iso: "BEL",
      phonePrefix: "56",
      sort: 10,
      isActive: false,
      latitude: 50.83,
      longitude: 4,
    },
    {
      name: "بلیز",
      nameEn: "Belize",
      slug: "belize",
      alphaTwo: "BZ",
      iso: "BLZ",
      phonePrefix: "84",
      sort: 10,
      isActive: false,
      latitude: 17.25,
      longitude: -88.75,
    },
    {
      name: "بنین",
      nameEn: "Benin",
      slug: "benin",
      alphaTwo: "BJ",
      iso: "BEN",
      phonePrefix: "204",
      sort: 10,
      isActive: false,
      latitude: 9.5,
      longitude: 2.25,
    },
    {
      name: "برمودا",
      nameEn: "Bermuda",
      slug: "bermuda",
      alphaTwo: "BM",
      iso: "BMU",
      phonePrefix: "60",
      sort: 10,
      isActive: false,
      latitude: 32.33,
      longitude: -64.75,
    },
    {
      name: "پادشاهی بوتان",
      nameEn: "Bhutan",
      slug: "bhutan",
      alphaTwo: "BT",
      iso: "BTN",
      phonePrefix: "64",
      sort: 10,
      isActive: false,
      latitude: 27.5,
      longitude: 90.5,
    },
    {
      name: "بولیوی",
      nameEn: "Bolivia, Plurinational State of",
      slug: "bolivia-plurinational-state-of",
      alphaTwo: "BO",
      iso: "BOL",
      phonePrefix: "68",
      sort: 10,
      isActive: false,
      latitude: -17,
      longitude: -65,
    },
    {
      name: "بوسنی و هرزگوین",
      nameEn: "Bosnia and Herzegovina",
      slug: "bosnia-and-herzegovina",
      alphaTwo: "BA",
      iso: "BIH",
      phonePrefix: "70",
      sort: 10,
      isActive: false,
      latitude: 44,
      longitude: 18,
    },
    {
      name: "بوتسوانا",
      nameEn: "Botswana",
      slug: "botswana",
      alphaTwo: "BW",
      iso: "BWA",
      phonePrefix: "72",
      sort: 10,
      isActive: false,
      latitude: -22,
      longitude: 24,
    },
    {
      name: "جزیره بووه",
      nameEn: "Bouvet Island",
      slug: "bouvet-island",
      alphaTwo: "BV",
      iso: "BVT",
      phonePrefix: "74",
      sort: 10,
      isActive: false,
      latitude: -54.43,
      longitude: 3.4,
    },
    {
      name: "برزیل",
      nameEn: "Brazil",
      slug: "brazil",
      alphaTwo: "BR",
      iso: "BRA",
      phonePrefix: "76",
      sort: 10,
      isActive: false,
      latitude: -10,
      longitude: -55,
    },
    {
      name: "قلمرو اقیانوس هند بر",
      nameEn: "British Indian Ocean Territory",
      slug: "british-indian-ocean-territory",
      alphaTwo: "IO",
      iso: "IOT",
      phonePrefix: "86",
      sort: 10,
      isActive: false,
      latitude: -6,
      longitude: 71.5,
    },
    {
      name: "برونئی",
      nameEn: "Brunei Darussalam",
      slug: "brunei-darussalam",
      alphaTwo: "BN",
      iso: "BRN",
      phonePrefix: "96",
      sort: 10,
      isActive: false,
      latitude: 4.5,
      longitude: 114.67,
    },
    {
      name: "بلغارستان",
      nameEn: "Bulgaria",
      slug: "bulgaria",
      alphaTwo: "BG",
      iso: "BGR",
      phonePrefix: "100",
      sort: 10,
      isActive: false,
      latitude: 43,
      longitude: 25,
    },
    {
      name: "بورکینافاسو",
      nameEn: "Burkina Faso",
      slug: "burkina-faso",
      alphaTwo: "BF",
      iso: "BFA",
      phonePrefix: "854",
      sort: 10,
      isActive: false,
      latitude: 13,
      longitude: -2,
    },
    {
      name: "بوروندی",
      nameEn: "Burundi",
      slug: "burundi",
      alphaTwo: "BI",
      iso: "BDI",
      phonePrefix: "108",
      sort: 10,
      isActive: false,
      latitude: -3.5,
      longitude: 30,
    },
    {
      name: "کامبوج",
      nameEn: "Cambodia",
      slug: "cambodia",
      alphaTwo: "KH",
      iso: "KHM",
      phonePrefix: "116",
      sort: 10,
      isActive: false,
      latitude: 13,
      longitude: 105,
    },
    {
      name: "کامرون",
      nameEn: "Cameroon",
      slug: "cameroon",
      alphaTwo: "CM",
      iso: "CMR",
      phonePrefix: "120",
      sort: 10,
      isActive: false,
      latitude: 6,
      longitude: 12,
    },
    {
      name: "کانادا",
      nameEn: "Canada",
      slug: "canada",
      alphaTwo: "CA",
      iso: "CAN",
      phonePrefix: "124",
      sort: 10,
      isActive: false,
      latitude: 60,
      longitude: -95,
    },
    {
      name: "کیپ ورد",
      nameEn: "Cape Verde",
      slug: "cape-verde",
      alphaTwo: "CV",
      iso: "CPV",
      phonePrefix: "132",
      sort: 10,
      isActive: false,
      latitude: 16,
      longitude: -24,
    },
    {
      name: "جزایر کیمن",
      nameEn: "Cayman Islands",
      slug: "cayman-islands",
      alphaTwo: "KY",
      iso: "CYM",
      phonePrefix: "136",
      sort: 10,
      isActive: false,
      latitude: 19.5,
      longitude: -80.5,
    },
    {
      name: "جمهوری آفریقای مرکزی",
      nameEn: "Central African Republic",
      slug: "central-african-republic",
      alphaTwo: "CF",
      iso: "CAF",
      phonePrefix: "140",
      sort: 10,
      isActive: false,
      latitude: 7,
      longitude: 21,
    },
    {
      name: "چاد",
      nameEn: "Chad",
      slug: "chad",
      alphaTwo: "TD",
      iso: "TCD",
      phonePrefix: "148",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: 19,
    },
    {
      name: "شیلی",
      nameEn: "Chile",
      slug: "chile",
      alphaTwo: "CL",
      iso: "CHL",
      phonePrefix: "152",
      sort: 10,
      isActive: false,
      latitude: -30,
      longitude: -71,
    },
    {
      name: "چین",
      nameEn: "China",
      slug: "china",
      alphaTwo: "CN",
      iso: "CHN",
      phonePrefix: "156",
      sort: 10,
      isActive: false,
      latitude: 35,
      longitude: 105,
    },
    {
      name: "جزیره کریسمس",
      nameEn: "Christmas Island",
      slug: "christmas-island",
      alphaTwo: "CX",
      iso: "CXR",
      phonePrefix: "162",
      sort: 10,
      isActive: false,
      latitude: -10.5,
      longitude: 105.67,
    },
    {
      name: "جزایر کوکوس",
      nameEn: "Cocos (Keeling) Islands",
      slug: "cocos-keeling-islands",
      alphaTwo: "CC",
      iso: "CCK",
      phonePrefix: "166",
      sort: 10,
      isActive: false,
      latitude: -12.5,
      longitude: 96.83,
    },
    {
      name: "کلمبیا",
      nameEn: "Colombia",
      slug: "colombia",
      alphaTwo: "CO",
      iso: "COL",
      phonePrefix: "170",
      sort: 10,
      isActive: false,
      latitude: 4,
      longitude: -72,
    },
    {
      name: "کومور",
      nameEn: "Comoros",
      slug: "comoros",
      alphaTwo: "KM",
      iso: "COM",
      phonePrefix: "174",
      sort: 10,
      isActive: false,
      latitude: -12.17,
      longitude: 44.25,
    },
    {
      name: "جمهوری کنگو",
      nameEn: "Congo",
      slug: "congo",
      alphaTwo: "CG",
      iso: "COG",
      phonePrefix: "178",
      sort: 10,
      isActive: false,
      latitude: -1,
      longitude: 15,
    },
    {
      name: "جمهوری دموکراتیک کنگ",
      nameEn: "Congo, the Democratic Republic of the",
      slug: "congo-the-democratic-republic-of-the",
      alphaTwo: "CD",
      iso: "COD",
      phonePrefix: "180",
      sort: 10,
      isActive: false,
      latitude: 0,
      longitude: 25,
    },
    {
      name: "جزایر کوک",
      nameEn: "Cook Islands",
      slug: "cook-islands",
      alphaTwo: "CK",
      iso: "COK",
      phonePrefix: "184",
      sort: 10,
      isActive: false,
      latitude: -21.23,
      longitude: -159.77,
    },
    {
      name: "کاستاریکا",
      nameEn: "Costa Rica",
      slug: "costa-rica",
      alphaTwo: "CR",
      iso: "CRI",
      phonePrefix: "188",
      sort: 10,
      isActive: false,
      latitude: 10,
      longitude: -84,
    },
    {
      name: "ساحل عاج",
      nameEn: "Côte d'Ivoire",
      slug: "cote-divoire",
      alphaTwo: "CI",
      iso: "CIV",
      phonePrefix: "384",
      sort: 10,
      isActive: false,
      latitude: 8,
      longitude: -5,
    },
    {
      name: "کرواسی",
      nameEn: "Croatia",
      slug: "croatia",
      alphaTwo: "HR",
      iso: "HRV",
      phonePrefix: "191",
      sort: 10,
      isActive: false,
      latitude: 45.17,
      longitude: 15.5,
    },
    {
      name: "کوبا",
      nameEn: "Cuba",
      slug: "cuba",
      alphaTwo: "CU",
      iso: "CUB",
      phonePrefix: "192",
      sort: 10,
      isActive: false,
      latitude: 21.5,
      longitude: -80,
    },
    {
      name: "قبرس",
      nameEn: "Cyprus",
      slug: "cyprus",
      alphaTwo: "CY",
      iso: "CYP",
      phonePrefix: "196",
      sort: 10,
      isActive: false,
      latitude: 35,
      longitude: 33,
    },
    {
      name: "جمهوری چک",
      nameEn: "Czech Republic",
      slug: "czech-republic",
      alphaTwo: "CZ",
      iso: "CZE",
      phonePrefix: "203",
      sort: 10,
      isActive: false,
      latitude: 49.75,
      longitude: 15.5,
    },
    {
      name: "دانمارک",
      nameEn: "Denmark",
      slug: "denmark",
      alphaTwo: "DK",
      iso: "DNK",
      phonePrefix: "208",
      sort: 10,
      isActive: false,
      latitude: 56,
      longitude: 10,
    },
    {
      name: "جیبوتی",
      nameEn: "Djibouti",
      slug: "djibouti",
      alphaTwo: "DJ",
      iso: "DJI",
      phonePrefix: "262",
      sort: 10,
      isActive: false,
      latitude: 11.5,
      longitude: 43,
    },
    {
      name: "دومینیکا",
      nameEn: "Dominica",
      slug: "dominica",
      alphaTwo: "DM",
      iso: "DMA",
      phonePrefix: "212",
      sort: 10,
      isActive: false,
      latitude: 15.42,
      longitude: -61.33,
    },
    {
      name: "جمهوری دومینیکن",
      nameEn: "Dominican Republic",
      slug: "dominican-republic",
      alphaTwo: "DO",
      iso: "DOM",
      phonePrefix: "214",
      sort: 10,
      isActive: false,
      latitude: 19,
      longitude: -70.67,
    },
    {
      name: "اکوادور",
      nameEn: "Ecuador",
      slug: "ecuador",
      alphaTwo: "EC",
      iso: "ECU",
      phonePrefix: "218",
      sort: 10,
      isActive: false,
      latitude: -2,
      longitude: -77.5,
    },
    {
      name: "مصر",
      nameEn: "Egypt",
      slug: "egypt",
      alphaTwo: "EG",
      iso: "EGY",
      phonePrefix: "818",
      sort: 10,
      isActive: false,
      latitude: 27,
      longitude: 30,
    },
    {
      name: "السالوادور",
      nameEn: "El Salvador",
      slug: "el-salvador",
      alphaTwo: "SV",
      iso: "SLV",
      phonePrefix: "222",
      sort: 10,
      isActive: false,
      latitude: 13.83,
      longitude: -88.92,
    },
    {
      name: "گینه استوایی",
      nameEn: "Equatorial Guinea",
      slug: "equatorial-guinea",
      alphaTwo: "GQ",
      iso: "GNQ",
      phonePrefix: "226",
      sort: 10,
      isActive: false,
      latitude: 2,
      longitude: 10,
    },
    {
      name: "اریتره",
      nameEn: "Eritrea",
      slug: "eritrea",
      alphaTwo: "ER",
      iso: "ERI",
      phonePrefix: "232",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: 39,
    },
    {
      name: "استونی",
      nameEn: "Estonia",
      slug: "estonia",
      alphaTwo: "EE",
      iso: "EST",
      phonePrefix: "233",
      sort: 10,
      isActive: false,
      latitude: 59,
      longitude: 26,
    },
    {
      name: "اتیوپی",
      nameEn: "Ethiopia",
      slug: "ethiopia",
      alphaTwo: "ET",
      iso: "ETH",
      phonePrefix: "231",
      sort: 10,
      isActive: false,
      latitude: 8,
      longitude: 38,
    },
    {
      name: "جزایر فالکند",
      nameEn: "Falkland Islands (Malvinas)",
      slug: "falkland-islands-malvinas",
      alphaTwo: "FK",
      iso: "FLK",
      phonePrefix: "238",
      sort: 10,
      isActive: false,
      latitude: -51.75,
      longitude: -59,
    },
    {
      name: "جزایر فارو",
      nameEn: "Faroe Islands",
      slug: "faroe-islands",
      alphaTwo: "FO",
      iso: "FRO",
      phonePrefix: "234",
      sort: 10,
      isActive: false,
      latitude: 62,
      longitude: -7,
    },
    {
      name: "فیجی",
      nameEn: "Fiji",
      slug: "fiji",
      alphaTwo: "FJ",
      iso: "FJI",
      phonePrefix: "242",
      sort: 10,
      isActive: false,
      latitude: -18,
      longitude: 175,
    },
    {
      name: "فنلاند",
      nameEn: "Finland",
      slug: "finland",
      alphaTwo: "FI",
      iso: "FIN",
      phonePrefix: "246",
      sort: 10,
      isActive: false,
      latitude: 64,
      longitude: 26,
    },
    {
      name: "فرانسه",
      nameEn: "France",
      slug: "france",
      alphaTwo: "FR",
      iso: "FRA",
      phonePrefix: "250",
      sort: 10,
      isActive: false,
      latitude: 46,
      longitude: 2,
    },
    {
      name: "گویان فرانسه",
      nameEn: "French Guiana",
      slug: "french-guiana",
      alphaTwo: "GF",
      iso: "GUF",
      phonePrefix: "254",
      sort: 10,
      isActive: false,
      latitude: 4,
      longitude: -53,
    },
    {
      name: "پولی‌نزی فرانسه",
      nameEn: "French Polynesia",
      slug: "french-polynesia",
      alphaTwo: "PF",
      iso: "PYF",
      phonePrefix: "258",
      sort: 10,
      isActive: false,
      latitude: -15,
      longitude: -140,
    },
    {
      name: "سرزمین‌های قطب جنوب ",
      nameEn: "French Southern Territories",
      slug: "french-southern-territories",
      alphaTwo: "TF",
      iso: "ATF",
      phonePrefix: "260",
      sort: 10,
      isActive: false,
      latitude: -43,
      longitude: 67,
    },
    {
      name: "گابون",
      nameEn: "Gabon",
      slug: "gabon",
      alphaTwo: "GA",
      iso: "GAB",
      phonePrefix: "266",
      sort: 10,
      isActive: false,
      latitude: -1,
      longitude: 11.75,
    },
    {
      name: "گامبیا",
      nameEn: "Gambia",
      slug: "gambia",
      alphaTwo: "GM",
      iso: "GMB",
      phonePrefix: "270",
      sort: 10,
      isActive: false,
      latitude: 13.47,
      longitude: -16.57,
    },
    {
      name: "گرجستان",
      nameEn: "Georgia",
      slug: "georgia",
      alphaTwo: "GE",
      iso: "GEO",
      phonePrefix: "268",
      sort: 10,
      isActive: false,
      latitude: 42,
      longitude: 43.5,
    },
    {
      name: "آلمان",
      nameEn: "Germany",
      slug: "germany",
      alphaTwo: "DE",
      iso: "DEU",
      phonePrefix: "276",
      sort: 10,
      isActive: false,
      latitude: 51,
      longitude: 9,
    },
    {
      name: "غنا",
      nameEn: "Ghana",
      slug: "ghana",
      alphaTwo: "GH",
      iso: "GHA",
      phonePrefix: "288",
      sort: 10,
      isActive: false,
      latitude: 8,
      longitude: -2,
    },
    {
      name: "جبل طارق",
      nameEn: "Gibraltar",
      slug: "gibraltar",
      alphaTwo: "GI",
      iso: "GIB",
      phonePrefix: "292",
      sort: 10,
      isActive: false,
      latitude: 36.18,
      longitude: -5.37,
    },
    {
      name: "یونان",
      nameEn: "Greece",
      slug: "greece",
      alphaTwo: "GR",
      iso: "GRC",
      phonePrefix: "300",
      sort: 10,
      isActive: false,
      latitude: 39,
      longitude: 22,
    },
    {
      name: "گرینلند",
      nameEn: "Greenland",
      slug: "greenland",
      alphaTwo: "GL",
      iso: "GRL",
      phonePrefix: "304",
      sort: 10,
      isActive: false,
      latitude: 72,
      longitude: -40,
    },
    {
      name: "گرنادا",
      nameEn: "Grenada",
      slug: "grenada",
      alphaTwo: "GD",
      iso: "GRD",
      phonePrefix: "308",
      sort: 10,
      isActive: false,
      latitude: 12.12,
      longitude: -61.67,
    },
    {
      name: "جزیره گوادلوپ",
      nameEn: "Guadeloupe",
      slug: "guadeloupe",
      alphaTwo: "GP",
      iso: "GLP",
      phonePrefix: "312",
      sort: 10,
      isActive: false,
      latitude: 16.25,
      longitude: -61.58,
    },
    {
      name: "گوآم",
      nameEn: "Guam",
      slug: "guam",
      alphaTwo: "GU",
      iso: "GUM",
      phonePrefix: "316",
      sort: 10,
      isActive: false,
      latitude: 13.47,
      longitude: 144.78,
    },
    {
      name: "گواتمالا",
      nameEn: "Guatemala",
      slug: "guatemala",
      alphaTwo: "GT",
      iso: "GTM",
      phonePrefix: "320",
      sort: 10,
      isActive: false,
      latitude: 15.5,
      longitude: -90.25,
    },
    {
      name: "گرنزی",
      nameEn: "Guernsey",
      slug: "guernsey",
      alphaTwo: "GG",
      iso: "GGY",
      phonePrefix: "831",
      sort: 10,
      isActive: false,
      latitude: 49.5,
      longitude: -2.56,
    },
    {
      name: "گینه",
      nameEn: "Guinea",
      slug: "guinea",
      alphaTwo: "GN",
      iso: "GIN",
      phonePrefix: "324",
      sort: 10,
      isActive: false,
      latitude: 11,
      longitude: -10,
    },
    {
      name: "گینه بیسائو",
      nameEn: "Guinea-Bissau",
      slug: "guineabissau",
      alphaTwo: "GW",
      iso: "GNB",
      phonePrefix: "624",
      sort: 10,
      isActive: false,
      latitude: 12,
      longitude: -15,
    },
    {
      name: "گویان",
      nameEn: "Guyana",
      slug: "guyana",
      alphaTwo: "GY",
      iso: "GUY",
      phonePrefix: "328",
      sort: 10,
      isActive: false,
      latitude: 5,
      longitude: -59,
    },
    {
      name: "هائیتی",
      nameEn: "Haiti",
      slug: "haiti",
      alphaTwo: "HT",
      iso: "HTI",
      phonePrefix: "332",
      sort: 10,
      isActive: false,
      latitude: 19,
      longitude: -72.42,
    },
    {
      name: "جزیره هرد و جزایر مک",
      nameEn: "Heard Island and McDonald Islands",
      slug: "heard-island-and-mcdonald-islands",
      alphaTwo: "HM",
      iso: "HMD",
      phonePrefix: "334",
      sort: 10,
      isActive: false,
      latitude: -53.1,
      longitude: 72.52,
    },
    {
      name: "واتیکان",
      nameEn: "Holy See (Vatican City State)",
      slug: "holy-see-vatican-city-state",
      alphaTwo: "VA",
      iso: "VAT",
      phonePrefix: "336",
      sort: 10,
      isActive: false,
      latitude: 41.9,
      longitude: 12.45,
    },
    {
      name: "هندوراس",
      nameEn: "Honduras",
      slug: "honduras",
      alphaTwo: "HN",
      iso: "HND",
      phonePrefix: "340",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: -86.5,
    },
    {
      name: "هنگ کنگ",
      nameEn: "Hong Kong",
      slug: "hong-kong",
      alphaTwo: "HK",
      iso: "HKG",
      phonePrefix: "344",
      sort: 10,
      isActive: false,
      latitude: 22.25,
      longitude: 114.17,
    },
    {
      name: "مجارستان",
      nameEn: "Hungary",
      slug: "hungary",
      alphaTwo: "HU",
      iso: "HUN",
      phonePrefix: "348",
      sort: 10,
      isActive: false,
      latitude: 47,
      longitude: 20,
    },
    {
      name: "ایسلند",
      nameEn: "Iceland",
      slug: "iceland",
      alphaTwo: "IS",
      iso: "ISL",
      phonePrefix: "352",
      sort: 10,
      isActive: false,
      latitude: 65,
      longitude: -18,
    },
    {
      name: "هند",
      nameEn: "India",
      slug: "india",
      alphaTwo: "IN",
      iso: "IND",
      phonePrefix: "356",
      sort: 10,
      isActive: false,
      latitude: 20,
      longitude: 77,
    },
    {
      name: "اندونزی",
      nameEn: "Indonesia",
      slug: "indonesia",
      alphaTwo: "ID",
      iso: "IDN",
      phonePrefix: "360",
      sort: 10,
      isActive: false,
      latitude: -5,
      longitude: 120,
    },
    {
      name: "عراق",
      nameEn: "Iraq",
      slug: "iraq",
      alphaTwo: "IQ",
      iso: "IRQ",
      phonePrefix: "368",
      sort: 10,
      isActive: false,
      latitude: 33,
      longitude: 44,
    },
    {
      name: "جمهوری ایرلند",
      nameEn: "Ireland",
      slug: "ireland",
      alphaTwo: "IE",
      iso: "IRL",
      phonePrefix: "372",
      sort: 10,
      isActive: false,
      latitude: 53,
      longitude: -8,
    },
    {
      name: "جزیره من",
      nameEn: "Isle of Man",
      slug: "isle-of-man",
      alphaTwo: "IM",
      iso: "IMN",
      phonePrefix: "833",
      sort: 10,
      isActive: false,
      latitude: 54.23,
      longitude: -4.55,
    },
    {
      name: "اسرائیل",
      nameEn: "Israel",
      slug: "israel",
      alphaTwo: "IL",
      iso: "ISR",
      phonePrefix: "376",
      sort: 10,
      isActive: false,
      latitude: 31.5,
      longitude: 34.75,
    },
    {
      name: "ایتالیا",
      nameEn: "Italy",
      slug: "italy",
      alphaTwo: "IT",
      iso: "ITA",
      phonePrefix: "380",
      sort: 10,
      isActive: false,
      latitude: 42.83,
      longitude: 12.83,
    },
    {
      name: "جامائیکا",
      nameEn: "Jamaica",
      slug: "jamaica",
      alphaTwo: "JM",
      iso: "JAM",
      phonePrefix: "388",
      sort: 10,
      isActive: false,
      latitude: 18.25,
      longitude: -77.5,
    },
    {
      name: "ژاپن",
      nameEn: "Japan",
      slug: "japan",
      alphaTwo: "JP",
      iso: "JPN",
      phonePrefix: "392",
      sort: 10,
      isActive: false,
      latitude: 36,
      longitude: 138,
    },
    {
      name: "جرسی",
      nameEn: "Jersey",
      slug: "jersey",
      alphaTwo: "JE",
      iso: "JEY",
      phonePrefix: "832",
      sort: 10,
      isActive: false,
      latitude: 49.21,
      longitude: -2.13,
    },
    {
      name: "اردن",
      nameEn: "Jordan",
      slug: "jordan",
      alphaTwo: "JO",
      iso: "JOR",
      phonePrefix: "400",
      sort: 10,
      isActive: false,
      latitude: 31,
      longitude: 36,
    },
    {
      name: "قزاقستان",
      nameEn: "Kazakhstan",
      slug: "kazakhstan",
      alphaTwo: "KZ",
      iso: "KAZ",
      phonePrefix: "398",
      sort: 10,
      isActive: false,
      latitude: 48,
      longitude: 68,
    },
    {
      name: "کنیا",
      nameEn: "Kenya",
      slug: "kenya",
      alphaTwo: "KE",
      iso: "KEN",
      phonePrefix: "404",
      sort: 10,
      isActive: false,
      latitude: 1,
      longitude: 38,
    },
    {
      name: "کیریباتی",
      nameEn: "Kiribati",
      slug: "kiribati",
      alphaTwo: "KI",
      iso: "KIR",
      phonePrefix: "296",
      sort: 10,
      isActive: false,
      latitude: 1.42,
      longitude: 173,
    },
    {
      name: "کره شمالی",
      nameEn: "Korea, Democratic People's Republic of",
      slug: "korea-democratic-peoples-republic-of",
      alphaTwo: "KP",
      iso: "PRK",
      phonePrefix: "408",
      sort: 10,
      isActive: false,
      latitude: 40,
      longitude: 127,
    },
    {
      name: "کره جنوبی",
      nameEn: "Korea, Republic of",
      slug: "korea-republic-of",
      alphaTwo: "KR",
      iso: "KOR",
      phonePrefix: "410",
      sort: 10,
      isActive: false,
      latitude: 37,
      longitude: 127.5,
    },
    {
      name: "کویت",
      nameEn: "Kuwait",
      slug: "kuwait",
      alphaTwo: "KW",
      iso: "KWT",
      phonePrefix: "414",
      sort: 10,
      isActive: false,
      latitude: 29.34,
      longitude: 47.66,
    },
    {
      name: "قرقیزستان",
      nameEn: "Kyrgyzstan",
      slug: "kyrgyzstan",
      alphaTwo: "KG",
      iso: "KGZ",
      phonePrefix: "417",
      sort: 10,
      isActive: false,
      latitude: 41,
      longitude: 75,
    },
    {
      name: "لائوس",
      nameEn: "Lao People's Democratic Republic",
      slug: "lao-peoples-democratic-republic",
      alphaTwo: "LA",
      iso: "LAO",
      phonePrefix: "418",
      sort: 10,
      isActive: false,
      latitude: 18,
      longitude: 105,
    },
    {
      name: "لتونی",
      nameEn: "Latvia",
      slug: "latvia",
      alphaTwo: "LV",
      iso: "LVA",
      phonePrefix: "428",
      sort: 10,
      isActive: false,
      latitude: 57,
      longitude: 25,
    },
    {
      name: "لبنان",
      nameEn: "Lebanon",
      slug: "lebanon",
      alphaTwo: "LB",
      iso: "LBN",
      phonePrefix: "422",
      sort: 10,
      isActive: false,
      latitude: 33.83,
      longitude: 35.83,
    },
    {
      name: "لسوتو",
      nameEn: "Lesotho",
      slug: "lesotho",
      alphaTwo: "LS",
      iso: "LSO",
      phonePrefix: "426",
      sort: 10,
      isActive: false,
      latitude: -29.5,
      longitude: 28.5,
    },
    {
      name: "لیبریا",
      nameEn: "Liberia",
      slug: "liberia",
      alphaTwo: "LR",
      iso: "LBR",
      phonePrefix: "430",
      sort: 10,
      isActive: false,
      latitude: 6.5,
      longitude: -9.5,
    },
    {
      name: "لیختن‌اشتاین",
      nameEn: "Liechtenstein",
      slug: "liechtenstein",
      alphaTwo: "LI",
      iso: "LIE",
      phonePrefix: "438",
      sort: 10,
      isActive: false,
      latitude: 47.17,
      longitude: 9.53,
    },
    {
      name: "لیتوانی",
      nameEn: "Lithuania",
      slug: "lithuania",
      alphaTwo: "LT",
      iso: "LTU",
      phonePrefix: "440",
      sort: 10,
      isActive: false,
      latitude: 56,
      longitude: 24,
    },
    {
      name: "لوکزامبورگ",
      nameEn: "Luxembourg",
      slug: "luxembourg",
      alphaTwo: "LU",
      iso: "LUX",
      phonePrefix: "442",
      sort: 10,
      isActive: false,
      latitude: 49.75,
      longitude: 6.17,
    },
    {
      name: "ماکائو",
      nameEn: "Macao",
      slug: "macao",
      alphaTwo: "MO",
      iso: "MAC",
      phonePrefix: "446",
      sort: 10,
      isActive: false,
      latitude: 22.17,
      longitude: 113.55,
    },
    {
      name: "مقدونیه",
      nameEn: "Macedonia, the former Yugoslav Republic of",
      slug: "macedonia-the-former-yugoslav-republic-of",
      alphaTwo: "MK",
      iso: "MKD",
      phonePrefix: "807",
      sort: 10,
      isActive: false,
      latitude: 41.83,
      longitude: 22,
    },
    {
      name: "ماداگاسکار",
      nameEn: "Madagascar",
      slug: "madagascar",
      alphaTwo: "MG",
      iso: "MDG",
      phonePrefix: "450",
      sort: 10,
      isActive: false,
      latitude: -20,
      longitude: 47,
    },
    {
      name: "مالاوی",
      nameEn: "Malawi",
      slug: "malawi",
      alphaTwo: "MW",
      iso: "MWI",
      phonePrefix: "454",
      sort: 10,
      isActive: false,
      latitude: -13.5,
      longitude: 34,
    },
    {
      name: "مالزی",
      nameEn: "Malaysia",
      slug: "malaysia",
      alphaTwo: "MY",
      iso: "MYS",
      phonePrefix: "458",
      sort: 10,
      isActive: false,
      latitude: 2.5,
      longitude: 112.5,
    },
    {
      name: "مالدیو",
      nameEn: "Maldives",
      slug: "maldives",
      alphaTwo: "MV",
      iso: "MDV",
      phonePrefix: "462",
      sort: 10,
      isActive: false,
      latitude: 3.25,
      longitude: 73,
    },
    {
      name: "مالی",
      nameEn: "Mali",
      slug: "mali",
      alphaTwo: "ML",
      iso: "MLI",
      phonePrefix: "466",
      sort: 10,
      isActive: false,
      latitude: 17,
      longitude: -4,
    },
    {
      name: "مالت",
      nameEn: "Malta",
      slug: "malta",
      alphaTwo: "MT",
      iso: "MLT",
      phonePrefix: "470",
      sort: 10,
      isActive: false,
      latitude: 35.83,
      longitude: 14.58,
    },
    {
      name: "جزایر مارشال",
      nameEn: "Marshall Islands",
      slug: "marshall-islands",
      alphaTwo: "MH",
      iso: "MHL",
      phonePrefix: "584",
      sort: 10,
      isActive: false,
      latitude: 9,
      longitude: 168,
    },
    {
      name: "مارتینیک",
      nameEn: "Martinique",
      slug: "martinique",
      alphaTwo: "MQ",
      iso: "MTQ",
      phonePrefix: "474",
      sort: 10,
      isActive: false,
      latitude: 14.67,
      longitude: -61,
    },
    {
      name: "موریتانی",
      nameEn: "Mauritania",
      slug: "mauritania",
      alphaTwo: "MR",
      iso: "MRT",
      phonePrefix: "478",
      sort: 10,
      isActive: false,
      latitude: 20,
      longitude: -12,
    },
    {
      name: "موریس",
      nameEn: "Mauritius",
      slug: "mauritius",
      alphaTwo: "MU",
      iso: "MUS",
      phonePrefix: "480",
      sort: 10,
      isActive: false,
      latitude: -20.28,
      longitude: 57.55,
    },
    {
      name: "مایوت",
      nameEn: "Mayotte",
      slug: "mayotte",
      alphaTwo: "YT",
      iso: "MYT",
      phonePrefix: "175",
      sort: 10,
      isActive: false,
      latitude: -12.83,
      longitude: 45.17,
    },
    {
      name: "مکزیک",
      nameEn: "Mexico",
      slug: "mexico",
      alphaTwo: "MX",
      iso: "MEX",
      phonePrefix: "484",
      sort: 10,
      isActive: false,
      latitude: 23,
      longitude: -102,
    },
    {
      name: "ایالات فدرال میکرونز",
      nameEn: "Micronesia, Federated States of",
      slug: "micronesia-federated-states-of",
      alphaTwo: "FM",
      iso: "FSM",
      phonePrefix: "583",
      sort: 10,
      isActive: false,
      latitude: 6.92,
      longitude: 158.25,
    },
    {
      name: "مولداوی",
      nameEn: "Moldova, Republic of",
      slug: "moldova-republic-of",
      alphaTwo: "MD",
      iso: "MDA",
      phonePrefix: "498",
      sort: 10,
      isActive: false,
      latitude: 47,
      longitude: 29,
    },
    {
      name: "موناکو",
      nameEn: "Monaco",
      slug: "monaco",
      alphaTwo: "MC",
      iso: "MCO",
      phonePrefix: "492",
      sort: 10,
      isActive: false,
      latitude: 43.73,
      longitude: 7.4,
    },
    {
      name: "مغولستان",
      nameEn: "Mongolia",
      slug: "mongolia",
      alphaTwo: "MN",
      iso: "MNG",
      phonePrefix: "496",
      sort: 10,
      isActive: false,
      latitude: 46,
      longitude: 105,
    },
    {
      name: "مونته‌نگرو",
      nameEn: "Montenegro",
      slug: "montenegro",
      alphaTwo: "ME",
      iso: "MNE",
      phonePrefix: "499",
      sort: 10,
      isActive: false,
      latitude: 42,
      longitude: 19,
    },
    {
      name: "مونتسرات",
      nameEn: "Montserrat",
      slug: "montserrat",
      alphaTwo: "MS",
      iso: "MSR",
      phonePrefix: "500",
      sort: 10,
      isActive: false,
      latitude: 16.75,
      longitude: -62.2,
    },
    {
      name: "مراکش",
      nameEn: "Morocco",
      slug: "morocco",
      alphaTwo: "MA",
      iso: "MAR",
      phonePrefix: "504",
      sort: 10,
      isActive: false,
      latitude: 32,
      longitude: -5,
    },
    {
      name: "موزامبیک",
      nameEn: "Mozambique",
      slug: "mozambique",
      alphaTwo: "MZ",
      iso: "MOZ",
      phonePrefix: "508",
      sort: 10,
      isActive: false,
      latitude: -18.25,
      longitude: 35,
    },
    {
      name: "میانمار",
      nameEn: "Myanmar",
      slug: "myanmar",
      alphaTwo: "MM",
      iso: "MMR",
      phonePrefix: "104",
      sort: 10,
      isActive: false,
      latitude: 22,
      longitude: 98,
    },
    {
      name: "نامیبیا",
      nameEn: "Namibia",
      slug: "namibia",
      alphaTwo: "NA",
      iso: "NAM",
      phonePrefix: "516",
      sort: 10,
      isActive: false,
      latitude: -22,
      longitude: 17,
    },
    {
      name: "نائورو",
      nameEn: "Nauru",
      slug: "nauru",
      alphaTwo: "NR",
      iso: "NRU",
      phonePrefix: "520",
      sort: 10,
      isActive: false,
      latitude: -0.53,
      longitude: 166.92,
    },
    {
      name: "نپال",
      nameEn: "Nepal",
      slug: "nepal",
      alphaTwo: "NP",
      iso: "NPL",
      phonePrefix: "524",
      sort: 10,
      isActive: false,
      latitude: 28,
      longitude: 84,
    },
    {
      name: "هلند",
      nameEn: "Netherlands",
      slug: "netherlands",
      alphaTwo: "NL",
      iso: "NLD",
      phonePrefix: "528",
      sort: 10,
      isActive: false,
      latitude: 52.5,
      longitude: 5.75,
    },
    {
      name: "آنتیل هلند",
      nameEn: "Netherlands Antilles",
      slug: "netherlands-antilles",
      alphaTwo: "AN",
      iso: "ANT",
      phonePrefix: "530",
      sort: 10,
      isActive: false,
      latitude: 12.25,
      longitude: -68.75,
    },
    {
      name: "کالدونیای جدید",
      nameEn: "New Caledonia",
      slug: "new-caledonia",
      alphaTwo: "NC",
      iso: "NCL",
      phonePrefix: "540",
      sort: 10,
      isActive: false,
      latitude: -21.5,
      longitude: 165.5,
    },
    {
      name: "نیوزیلند",
      nameEn: "New Zealand",
      slug: "new-zealand",
      alphaTwo: "NZ",
      iso: "NZL",
      phonePrefix: "554",
      sort: 10,
      isActive: false,
      latitude: -41,
      longitude: 174,
    },
    {
      name: "نیکاراگوئه",
      nameEn: "Nicaragua",
      slug: "nicaragua",
      alphaTwo: "NI",
      iso: "NIC",
      phonePrefix: "558",
      sort: 10,
      isActive: false,
      latitude: 13,
      longitude: -85,
    },
    {
      name: "نیجر",
      nameEn: "Niger",
      slug: "niger",
      alphaTwo: "NE",
      iso: "NER",
      phonePrefix: "562",
      sort: 10,
      isActive: false,
      latitude: 16,
      longitude: 8,
    },
    {
      name: "نیجریه",
      nameEn: "Nigeria",
      slug: "nigeria",
      alphaTwo: "NG",
      iso: "NGA",
      phonePrefix: "566",
      sort: 10,
      isActive: false,
      latitude: 10,
      longitude: 8,
    },
    {
      name: "نیووی",
      nameEn: "Niue",
      slug: "niue",
      alphaTwo: "NU",
      iso: "NIU",
      phonePrefix: "570",
      sort: 10,
      isActive: false,
      latitude: -19.03,
      longitude: -169.87,
    },
    {
      name: "جزیره نورفولک",
      nameEn: "Norfolk Island",
      slug: "norfolk-island",
      alphaTwo: "NF",
      iso: "NFK",
      phonePrefix: "574",
      sort: 10,
      isActive: false,
      latitude: -29.03,
      longitude: 167.95,
    },
    {
      name: "جزایر ماریانای شمالی",
      nameEn: "Northern Mariana Islands",
      slug: "northern-mariana-islands",
      alphaTwo: "MP",
      iso: "MNP",
      phonePrefix: "580",
      sort: 10,
      isActive: false,
      latitude: 15.2,
      longitude: 145.75,
    },
    {
      name: "نروژ",
      nameEn: "Norway",
      slug: "norway",
      alphaTwo: "NO",
      iso: "NOR",
      phonePrefix: "578",
      sort: 10,
      isActive: false,
      latitude: 62,
      longitude: 10,
    },
    {
      name: "عمان",
      nameEn: "Oman",
      slug: "oman",
      alphaTwo: "OM",
      iso: "OMN",
      phonePrefix: "512",
      sort: 10,
      isActive: false,
      latitude: 21,
      longitude: 57,
    },
    {
      name: "پاکستان",
      nameEn: "Pakistan",
      slug: "pakistan",
      alphaTwo: "PK",
      iso: "PAK",
      phonePrefix: "586",
      sort: 10,
      isActive: false,
      latitude: 30,
      longitude: 70,
    },
    {
      name: "پالائو",
      nameEn: "Palau",
      slug: "palau",
      alphaTwo: "PW",
      iso: "PLW",
      phonePrefix: "585",
      sort: 10,
      isActive: false,
      latitude: 7.5,
      longitude: 134.5,
    },
    {
      name: "فلسطین",
      nameEn: "Palestinian Territory, Occupied",
      slug: "palestinian-territory-occupied",
      alphaTwo: "PS",
      iso: "PSE",
      phonePrefix: "275",
      sort: 10,
      isActive: false,
      latitude: 32,
      longitude: 35.25,
    },
    {
      name: "پاناما",
      nameEn: "Panama",
      slug: "panama",
      alphaTwo: "PA",
      iso: "PAN",
      phonePrefix: "591",
      sort: 10,
      isActive: false,
      latitude: 9,
      longitude: -80,
    },
    {
      name: "پاپوآ گینه نو",
      nameEn: "Papua New Guinea",
      slug: "papua-new-guinea",
      alphaTwo: "PG",
      iso: "PNG",
      phonePrefix: "598",
      sort: 10,
      isActive: false,
      latitude: -6,
      longitude: 147,
    },
    {
      name: "پاراگوئه",
      nameEn: "Paraguay",
      slug: "paraguay",
      alphaTwo: "PY",
      iso: "PRY",
      phonePrefix: "600",
      sort: 10,
      isActive: false,
      latitude: -23,
      longitude: -58,
    },
    {
      name: "پرو",
      nameEn: "Peru",
      slug: "peru",
      alphaTwo: "PE",
      iso: "PER",
      phonePrefix: "604",
      sort: 10,
      isActive: false,
      latitude: -10,
      longitude: -76,
    },
    {
      name: "فیلیپین",
      nameEn: "Philippines",
      slug: "philippines",
      alphaTwo: "PH",
      iso: "PHL",
      phonePrefix: "608",
      sort: 10,
      isActive: false,
      latitude: 13,
      longitude: 122,
    },
    {
      name: "جزایر پیت‌کرن",
      nameEn: "Pitcairn",
      slug: "pitcairn",
      alphaTwo: "PN",
      iso: "PCN",
      phonePrefix: "612",
      sort: 10,
      isActive: false,
      latitude: -24.7,
      longitude: -127.4,
    },
    {
      name: "لهستان",
      nameEn: "Poland",
      slug: "poland",
      alphaTwo: "PL",
      iso: "POL",
      phonePrefix: "616",
      sort: 10,
      isActive: false,
      latitude: 52,
      longitude: 20,
    },
    {
      name: "پرتغال",
      nameEn: "Portugal",
      slug: "portugal",
      alphaTwo: "PT",
      iso: "PRT",
      phonePrefix: "620",
      sort: 10,
      isActive: false,
      latitude: 39.5,
      longitude: -8,
    },
    {
      name: "پورتوریکو",
      nameEn: "Puerto Rico",
      slug: "puerto-rico",
      alphaTwo: "PR",
      iso: "PRI",
      phonePrefix: "630",
      sort: 10,
      isActive: false,
      latitude: 18.25,
      longitude: -66.5,
    },
    {
      name: "قطر",
      nameEn: "Qatar",
      slug: "qatar",
      alphaTwo: "QA",
      iso: "QAT",
      phonePrefix: "634",
      sort: 10,
      isActive: false,
      latitude: 25.5,
      longitude: 51.25,
    },
    {
      name: "رئونیون",
      nameEn: "Réunion",
      slug: "reunion",
      alphaTwo: "RE",
      iso: "REU",
      phonePrefix: "638",
      sort: 10,
      isActive: false,
      latitude: -21.1,
      longitude: 55.6,
    },
    {
      name: "رومانی",
      nameEn: "Romania",
      slug: "romania",
      alphaTwo: "RO",
      iso: "ROU",
      phonePrefix: "642",
      sort: 10,
      isActive: false,
      latitude: 46,
      longitude: 25,
    },
    {
      name: "روسیه",
      nameEn: "Russian Federation",
      slug: "russian-federation",
      alphaTwo: "RU",
      iso: "RUS",
      phonePrefix: "643",
      sort: 10,
      isActive: false,
      latitude: 60,
      longitude: 100,
    },
    {
      name: "رواندا",
      nameEn: "Rwanda",
      slug: "rwanda",
      alphaTwo: "RW",
      iso: "RWA",
      phonePrefix: "646",
      sort: 10,
      isActive: false,
      latitude: -2,
      longitude: 30,
    },
    {
      name: "سنت بارثلمی",
      nameEn: "Saint Barthelemy",
      slug: "saint-barthelemy",
      alphaTwo: "BL",
      iso: "BLM",
      phonePrefix: "590",
      sort: 10,
      isActive: false,
      latitude: null,
      longitude: null,
    },
    {
      name: "سینت هلینا",
      nameEn: "Saint Helena, Ascension and Tristan da Cunha",
      slug: "saint-helena-ascension-and-tristan-da-cunha",
      alphaTwo: "SH",
      iso: "SHN",
      phonePrefix: "654",
      sort: 10,
      isActive: false,
      latitude: -15.93,
      longitude: -5.7,
    },
    {
      name: "سنت کیتس و نویس",
      nameEn: "Saint Kitts and Nevis",
      slug: "saint-kitts-and-nevis",
      alphaTwo: "KN",
      iso: "KNA",
      phonePrefix: "659",
      sort: 10,
      isActive: false,
      latitude: 17.33,
      longitude: -62.75,
    },
    {
      name: "سنت لوسیا",
      nameEn: "Saint Lucia",
      slug: "saint-lucia",
      alphaTwo: "LC",
      iso: "LCA",
      phonePrefix: "662",
      sort: 10,
      isActive: false,
      latitude: 13.88,
      longitude: -61.13,
    },
    {
      name: "سنت مارتین (فرانسوی)",
      nameEn: "Saint Martin (French Part)",
      slug: "saint-martin-french-part",
      alphaTwo: "MF",
      iso: "MAF",
      phonePrefix: "590",
      sort: 10,
      isActive: false,
      latitude: null,
      longitude: null,
    },
    {
      name: "سنت پیر و ماژلان",
      nameEn: "Saint Pierre and Miquelon",
      slug: "saint-pierre-and-miquelon",
      alphaTwo: "PM",
      iso: "SPM",
      phonePrefix: "666",
      sort: 10,
      isActive: false,
      latitude: 46.83,
      longitude: -56.33,
    },
    {
      name: "سنت وینسنت و گرنادین",
      nameEn: "Saint Vincent and the Grenadines",
      slug: "saint-vincent-and-the-grenadines",
      alphaTwo: "VC",
      iso: "VCT",
      phonePrefix: "670",
      sort: 10,
      isActive: false,
      latitude: 13.25,
      longitude: -61.2,
    },
    {
      name: "ساموآ",
      nameEn: "Samoa",
      slug: "samoa",
      alphaTwo: "WS",
      iso: "WSM",
      phonePrefix: "882",
      sort: 10,
      isActive: false,
      latitude: -13.58,
      longitude: -172.33,
    },
    {
      name: "سن مارینو",
      nameEn: "San Marino",
      slug: "san-marino",
      alphaTwo: "SM",
      iso: "SMR",
      phonePrefix: "674",
      sort: 10,
      isActive: false,
      latitude: 43.77,
      longitude: 12.42,
    },
    {
      name: "سائوتومه و پرنسیپ",
      nameEn: "Sao Tome and Principe",
      slug: "sao-tome-and-principe",
      alphaTwo: "ST",
      iso: "STP",
      phonePrefix: "678",
      sort: 10,
      isActive: false,
      latitude: 1,
      longitude: 7,
    },
    {
      name: "عربستان سعودی",
      nameEn: "Saudi Arabia",
      slug: "saudi-arabia",
      alphaTwo: "SA",
      iso: "SAU",
      phonePrefix: "682",
      sort: 10,
      isActive: false,
      latitude: 25,
      longitude: 45,
    },
    {
      name: "سنگال",
      nameEn: "Senegal",
      slug: "senegal",
      alphaTwo: "SN",
      iso: "SEN",
      phonePrefix: "686",
      sort: 10,
      isActive: false,
      latitude: 14,
      longitude: -14,
    },
    {
      name: "صربستان",
      nameEn: "Serbia",
      slug: "serbia",
      alphaTwo: "RS",
      iso: "SRB",
      phonePrefix: "688",
      sort: 10,
      isActive: false,
      latitude: 44,
      longitude: 21,
    },
    {
      name: "سیشل",
      nameEn: "Seychelles",
      slug: "seychelles",
      alphaTwo: "SC",
      iso: "SYC",
      phonePrefix: "690",
      sort: 10,
      isActive: false,
      latitude: -4.58,
      longitude: 55.67,
    },
    {
      name: "سیرالئون",
      nameEn: "Sierra Leone",
      slug: "sierra-leone",
      alphaTwo: "SL",
      iso: "SLE",
      phonePrefix: "694",
      sort: 10,
      isActive: false,
      latitude: 8.5,
      longitude: -11.5,
    },
    {
      name: "سنگاپور",
      nameEn: "Singapore",
      slug: "singapore",
      alphaTwo: "SG",
      iso: "SGP",
      phonePrefix: "702",
      sort: 10,
      isActive: false,
      latitude: 1.37,
      longitude: 103.8,
    },
    {
      name: "اسلواکی",
      nameEn: "Slovakia",
      slug: "slovakia",
      alphaTwo: "SK",
      iso: "SVK",
      phonePrefix: "703",
      sort: 10,
      isActive: false,
      latitude: 48.67,
      longitude: 19.5,
    },
    {
      name: "اسلوونی",
      nameEn: "Slovenia",
      slug: "slovenia",
      alphaTwo: "SI",
      iso: "SVN",
      phonePrefix: "705",
      sort: 10,
      isActive: false,
      latitude: 46,
      longitude: 15,
    },
    {
      name: "جزایر سلیمان",
      nameEn: "Solomon Islands",
      slug: "solomon-islands",
      alphaTwo: "SB",
      iso: "SLB",
      phonePrefix: "90",
      sort: 10,
      isActive: false,
      latitude: -8,
      longitude: 159,
    },
    {
      name: "سومالی",
      nameEn: "Somalia",
      slug: "somalia",
      alphaTwo: "SO",
      iso: "SOM",
      phonePrefix: "706",
      sort: 10,
      isActive: false,
      latitude: 10,
      longitude: 49,
    },
    {
      name: "آفریقای جنوبی",
      nameEn: "South Africa",
      slug: "south-africa",
      alphaTwo: "ZA",
      iso: "ZAF",
      phonePrefix: "710",
      sort: 10,
      isActive: false,
      latitude: -29,
      longitude: 24,
    },
    {
      name: "جورجیای جنوبی و جزای",
      nameEn: "South Georgia and the South Sandwich Islands",
      slug: "south-georgia-and-the-south-sandwich-islands",
      alphaTwo: "GS",
      iso: "SGS",
      phonePrefix: "239",
      sort: 10,
      isActive: false,
      latitude: -54.5,
      longitude: -37,
    },
    {
      name: "اسپانیا",
      nameEn: "Spain",
      slug: "spain",
      alphaTwo: "ES",
      iso: "ESP",
      phonePrefix: "724",
      sort: 10,
      isActive: false,
      latitude: 40,
      longitude: -4,
    },
    {
      name: "سری‌لانکا",
      nameEn: "Sri Lanka",
      slug: "sri-lanka",
      alphaTwo: "LK",
      iso: "LKA",
      phonePrefix: "144",
      sort: 10,
      isActive: false,
      latitude: 7,
      longitude: 81,
    },
    {
      name: "سودان",
      nameEn: "Sudan",
      slug: "sudan",
      alphaTwo: "SD",
      iso: "SDN",
      phonePrefix: "736",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: 30,
    },
    {
      name: "سورینام",
      nameEn: "Suriname",
      slug: "suriname",
      alphaTwo: "SR",
      iso: "SUR",
      phonePrefix: "740",
      sort: 10,
      isActive: false,
      latitude: 4,
      longitude: -56,
    },
    {
      name: "سوالبارد و یان ماین",
      nameEn: "Svalbard and Jan Mayen",
      slug: "svalbard-and-jan-mayen",
      alphaTwo: "SJ",
      iso: "SJM",
      phonePrefix: "744",
      sort: 10,
      isActive: false,
      latitude: 78,
      longitude: 20,
    },
    {
      name: "سوازیلند",
      nameEn: "Swaziland",
      slug: "swaziland",
      alphaTwo: "SZ",
      iso: "SWZ",
      phonePrefix: "748",
      sort: 10,
      isActive: false,
      latitude: -26.5,
      longitude: 31.5,
    },
    {
      name: "سوئد",
      nameEn: "Sweden",
      slug: "sweden",
      alphaTwo: "SE",
      iso: "SWE",
      phonePrefix: "752",
      sort: 10,
      isActive: false,
      latitude: 62,
      longitude: 15,
    },
    {
      name: "سوئیس",
      nameEn: "Switzerland",
      slug: "switzerland",
      alphaTwo: "CH",
      iso: "CHE",
      phonePrefix: "756",
      sort: 10,
      isActive: false,
      latitude: 47,
      longitude: 8,
    },
    {
      name: "سوریه",
      nameEn: "Syrian Arab Republic",
      slug: "syrian-arab-republic",
      alphaTwo: "SY",
      iso: "SYR",
      phonePrefix: "760",
      sort: 10,
      isActive: false,
      latitude: 35,
      longitude: 38,
    },
    {
      name: "تاجیکستان",
      nameEn: "Tajikistan",
      slug: "tajikistan",
      alphaTwo: "TJ",
      iso: "TJK",
      phonePrefix: "762",
      sort: 10,
      isActive: false,
      latitude: 39,
      longitude: 71,
    },
    {
      name: "تانزانیا",
      nameEn: "Tanzania, United Republic of",
      slug: "tanzania-united-republic-of",
      alphaTwo: "TZ",
      iso: "TZA",
      phonePrefix: "834",
      sort: 10,
      isActive: false,
      latitude: -6,
      longitude: 35,
    },
    {
      name: "تایلند",
      nameEn: "Thailand",
      slug: "thailand",
      alphaTwo: "TH",
      iso: "THA",
      phonePrefix: "764",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: 100,
    },
    {
      name: "تیمور شرقی",
      nameEn: "Timor-Leste",
      slug: "timorleste",
      alphaTwo: "TL",
      iso: "TLS",
      phonePrefix: "626",
      sort: 10,
      isActive: false,
      latitude: -8.55,
      longitude: 125.52,
    },
    {
      name: "توگو",
      nameEn: "Togo",
      slug: "togo",
      alphaTwo: "TG",
      iso: "TGO",
      phonePrefix: "768",
      sort: 10,
      isActive: false,
      latitude: 8,
      longitude: 1.17,
    },
    {
      name: "توکلائو",
      nameEn: "Tokelau",
      slug: "tokelau",
      alphaTwo: "TK",
      iso: "TKL",
      phonePrefix: "772",
      sort: 10,
      isActive: false,
      latitude: -9,
      longitude: -172,
    },
    {
      name: "تونگا",
      nameEn: "Tonga",
      slug: "tonga",
      alphaTwo: "TO",
      iso: "TON",
      phonePrefix: "776",
      sort: 10,
      isActive: false,
      latitude: -20,
      longitude: -175,
    },
    {
      name: "ترینیداد و توباگو",
      nameEn: "Trinidad and Tobago",
      slug: "trinidad-and-tobago",
      alphaTwo: "TT",
      iso: "TTO",
      phonePrefix: "780",
      sort: 10,
      isActive: false,
      latitude: 11,
      longitude: -61,
    },
    {
      name: "تونس",
      nameEn: "Tunisia",
      slug: "tunisia",
      alphaTwo: "TN",
      iso: "TUN",
      phonePrefix: "788",
      sort: 10,
      isActive: false,
      latitude: 34,
      longitude: 9,
    },
    {
      name: "ترکیه",
      nameEn: "Turkey",
      slug: "turkey",
      alphaTwo: "TR",
      iso: "TUR",
      phonePrefix: "792",
      sort: 10,
      isActive: false,
      latitude: 39,
      longitude: 35,
    },
    {
      name: "ترکمنستان",
      nameEn: "Turkmenistan",
      slug: "turkmenistan",
      alphaTwo: "TM",
      iso: "TKM",
      phonePrefix: "795",
      sort: 10,
      isActive: false,
      latitude: 40,
      longitude: 60,
    },
    {
      name: "جزایر تورکس و کایکوس",
      nameEn: "Turks and Caicos Islands",
      slug: "turks-and-caicos-islands",
      alphaTwo: "TC",
      iso: "TCA",
      phonePrefix: "796",
      sort: 10,
      isActive: false,
      latitude: 21.75,
      longitude: -71.58,
    },
    {
      name: "تووالو",
      nameEn: "Tuvalu",
      slug: "tuvalu",
      alphaTwo: "TV",
      iso: "TUV",
      phonePrefix: "798",
      sort: 10,
      isActive: false,
      latitude: -8,
      longitude: 178,
    },
    {
      name: "اوگاندا",
      nameEn: "Uganda",
      slug: "uganda",
      alphaTwo: "UG",
      iso: "UGA",
      phonePrefix: "800",
      sort: 10,
      isActive: false,
      latitude: 1,
      longitude: 32,
    },
    {
      name: "اوکراین",
      nameEn: "Ukraine",
      slug: "ukraine",
      alphaTwo: "UA",
      iso: "UKR",
      phonePrefix: "804",
      sort: 10,
      isActive: false,
      latitude: 49,
      longitude: 32,
    },
    {
      name: "امارات متحده عربی",
      nameEn: "United Arab Emirates",
      slug: "united-arab-emirates",
      alphaTwo: "AE",
      iso: "ARE",
      phonePrefix: "784",
      sort: 10,
      isActive: false,
      latitude: 24,
      longitude: 54,
    },
    {
      name: "بریتانیا",
      nameEn: "United Kingdom",
      slug: "united-kingdom",
      alphaTwo: "GB",
      iso: "GBR",
      phonePrefix: "826",
      sort: 10,
      isActive: false,
      latitude: 54,
      longitude: -2,
    },
    {
      name: "ایالات متحده آمریکا",
      nameEn: "United States",
      slug: "united-states",
      alphaTwo: "US",
      iso: "USA",
      phonePrefix: "840",
      sort: 10,
      isActive: false,
      latitude: 38,
      longitude: -97,
    },
    {
      name: "جزایر کوچک حاشیه‌ای ",
      nameEn: "United States Minor Outlying Islands",
      slug: "united-states-minor-outlying-islands",
      alphaTwo: "UM",
      iso: "UMI",
      phonePrefix: "581",
      sort: 10,
      isActive: false,
      latitude: 19.28,
      longitude: 166.6,
    },
    {
      name: "اروگوئه",
      nameEn: "Uruguay",
      slug: "uruguay",
      alphaTwo: "UY",
      iso: "URY",
      phonePrefix: "858",
      sort: 10,
      isActive: false,
      latitude: -33,
      longitude: -56,
    },
    {
      name: "ازبکستان",
      nameEn: "Uzbekistan",
      slug: "uzbekistan",
      alphaTwo: "UZ",
      iso: "UZB",
      phonePrefix: "860",
      sort: 10,
      isActive: false,
      latitude: 41,
      longitude: 64,
    },
    {
      name: "وانواتو",
      nameEn: "Vanuatu",
      slug: "vanuatu",
      alphaTwo: "VU",
      iso: "VUT",
      phonePrefix: "548",
      sort: 10,
      isActive: false,
      latitude: -16,
      longitude: 167,
    },
    {
      name: "ونزوئلا",
      nameEn: "Venezuela, Bolivarian Republic of",
      slug: "venezuela-bolivarian-republic-of",
      alphaTwo: "VE",
      iso: "VEN",
      phonePrefix: "862",
      sort: 10,
      isActive: false,
      latitude: 8,
      longitude: -66,
    },
    {
      name: "ویتنام",
      nameEn: "Viet Nam",
      slug: "viet-nam",
      alphaTwo: "VN",
      iso: "VNM",
      phonePrefix: "704",
      sort: 10,
      isActive: false,
      latitude: 16,
      longitude: 106,
    },
    {
      name: "جزایر ویرجین انگلستا",
      nameEn: "Virgin Islands, British",
      slug: "virgin-islands-british",
      alphaTwo: "VG",
      iso: "VGB",
      phonePrefix: "92",
      sort: 10,
      isActive: false,
      latitude: 18.5,
      longitude: -64.5,
    },
    {
      name: "جزایر ویرجین ایالات ",
      nameEn: "Virgin Islands, U.S.",
      slug: "virgin-islands-us",
      alphaTwo: "VI",
      iso: "VIR",
      phonePrefix: "850",
      sort: 10,
      isActive: false,
      latitude: 18.33,
      longitude: -64.83,
    },
    {
      name: "والیس و فوتونا",
      nameEn: "Wallis and Futuna",
      slug: "wallis-and-futuna",
      alphaTwo: "WF",
      iso: "WLF",
      phonePrefix: "876",
      sort: 10,
      isActive: false,
      latitude: -13.3,
      longitude: -176.2,
    },
    {
      name: "صحرای غربی",
      nameEn: "Western Sahara",
      slug: "western-sahara",
      alphaTwo: "EH",
      iso: "ESH",
      phonePrefix: "732",
      sort: 10,
      isActive: false,
      latitude: 24.5,
      longitude: -13,
    },
    {
      name: "یمن",
      nameEn: "Yemen",
      slug: "yemen",
      alphaTwo: "YE",
      iso: "YEM",
      phonePrefix: "887",
      sort: 10,
      isActive: false,
      latitude: 15,
      longitude: 48,
    },
    {
      name: "زامبیا",
      nameEn: "Zambia",
      slug: "zambia",
      alphaTwo: "ZM",
      iso: "ZMB",
      phonePrefix: "894",
      sort: 10,
      isActive: false,
      latitude: -15,
      longitude: 30,
    },
    {
      name: "زیمبابوه",
      nameEn: "Zimbabwe",
      slug: "zimbabwe",
      alphaTwo: "ZW",
      iso: "ZWE",
      phonePrefix: "716",
      sort: 10,
      isActive: false,
      latitude: -20,
      longitude: 30,
    },
    {
      name: "ایران",
      nameEn: "Iran, Islamic Republic of",
      slug: "iran-islamic-republic-of",
      alphaTwo: "IR",
      iso: "IRI",
      phonePrefix: "98",
      sort: 1,
      isActive: true,
      latitude: 32,
      longitude: 53,
    },
    {
      name: "لیبی",
      nameEn: "Libya",
      slug: "libya",
      alphaTwo: "LY",
      iso: "LBY",
      phonePrefix: "434",
      sort: 10,
      isActive: false,
      latitude: 25,
      longitude: 17,
    },
    {
      name: "تایوان",
      nameEn: "Taiwan",
      slug: "taiwan",
      alphaTwo: "TW",
      iso: "TWN",
      phonePrefix: "158",
      sort: 10,
      isActive: false,
      latitude: 23.5,
      longitude: 121,
    },
    {
      name: "جزایر بونیره و سبا",
      nameEn: "Bonaire, Sint Eustatius and Saba",
      slug: "bonaire-sint-eustatius-and-saba",
      alphaTwo: "BQ",
      iso: "BQQx",
      phonePrefix: "599",
      sort: 10,
      isActive: false,
      latitude: null,
      longitude: null,
    },
    {
      name: "کوراکائو",
      nameEn: "Curacao",
      slug: "curacao",
      alphaTwo: "CW",
      iso: "CWWx",
      phonePrefix: "599",
      sort: 0,
      isActive: false,
      latitude: null,
      longitude: null,
    },
    {
      name: "سینت مارتین (هلند)",
      nameEn: "Sint Maarten (Dutch Part)",
      slug: "sint-maarten-dutch-part",
      alphaTwo: "SX",
      iso: "SXXx",
      phonePrefix: "1",
      sort: 0,
      isActive: false,
      latitude: null,
      longitude: null,
    },
  ];

  constructor(
    @InjectRepository(Country)
    private countryRepository: Repository<Country>,
  ) {}

  async run(): Promise<any> {
    await this.countryRepository.upsert(this.data, {
      conflictPaths: ["name"],
      skipUpdateIfNoValuesChanged: true,
    });
  }
}
